services:
  Danilovl\RenderServiceTwigExtensionBundle\Twig\AsAttributeTwigExtension:
    autowire: true
    arguments:
      $container: '@service_container'
    public: true
    tags:
      - { name: twig.extension }

  Danilovl\RenderServiceTwigExtensionBundle\Service\TwigExtensionContainer:
    public: public
