services:
  danilovl_render_service_twig_extension:
    class: Danilovl\RenderServiceTwigExtensionBundle\Twig\RenderServiceExtension
    autowire: true
    public: false
    tags:
      - { name: twig.extension }
