services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Danilovl\RenderServiceTwigExtensionBundle\Twig\AsAttributeTwigExtension:
    arguments:
      $container: '@service_container'
    tags:
      - { name: twig.extension }

  Danilovl\RenderServiceTwigExtensionBundle\Service\TwigExtensionContainer:

  Danilovl\RenderServiceTwigExtensionBundle\Command\ListCommand:
